In [1]:
import numpy as np
A = np.array([
    [3,7],
    [-4,-6],
    [7,8],
    [1,-1],
    [-4,-1],
    [-3,-7]
])

In [2]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [4]:
A.shape

(6, 2)

In [5]:
 import pandas as pd

In [6]:
pd.DataFrame(A, columns=['a0','a1'])

a0  a1
0   3   7
1  -4  -6
2   7   8
3   1  -1
4  -4  -1
5  -3  -7

In [7]:
df = pd.DataFrame(A, columns=['a0','a1'])

In [8]:
df

a0  a1
0   3   7
1  -4  -6
2   7   8
3   1  -1
4  -4  -1
5  -3  -7

In [9]:
# we are going to get rel bew a0 and a1
# how 3 is changing with 7

In [11]:
#data having positive covrience one unit change slope change
#Anothe covarience in mixed data
# y =mx + c --> m is slope

In [12]:
# covrience9A0,A1 column num - cov = 0 in this example like 3-0, -4 - 0
# corvv --> = 25

In [13]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [15]:
a0=A[:,0]
a1 = A[:,1]

In [16]:
a0

array([ 3, -4,  7,  1, -4, -3])

In [17]:
a1

array([ 7, -6,  8, -1, -1, -7])

In [18]:
np.cov(a0,a1)        # --> a0  a1 --> below values
                     #     a0
                     #     a1 

array([[20., 25.],
       [25., 40.]])

In [20]:
np.sum(a0*a1)/5 # Manual

25.0

In [21]:
# transpose of metrix also can get cov

In [22]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [23]:
A.T

array([[ 3, -4,  7,  1, -4, -3],
       [ 7, -6,  8, -1, -1, -7]])

In [30]:
A.T@ A /5

array([[20., 25.],
       [25., 40.]])

In [26]:
# why we are using it

In [27]:
# eigen value
# Eigen vector

In [28]:
# (T(y = ?v))
"""
x1  x2
2   4
4   8
3   6
8   16
"""

'\nx1  x2\n2   4\n4   8\n3   6\n8   16\n'

In [31]:
sigma = A.T@ A /5

In [32]:
np.linalg.eig(sigma) # relation bw a0 and a1

(array([ 3.07417596, 56.92582404]),
 array([[-0.82806723, -0.56062881],
        [ 0.56062881, -0.82806723]]))

In [33]:
# highest value 

In [34]:
l , x = np.linalg.eig(sigma)

In [35]:
l

array([ 3.07417596, 56.92582404])

In [36]:
x

array([[-0.82806723, -0.56062881],
       [ 0.56062881, -0.82806723]])

In [37]:
sigma

array([[20., 25.],
       [25., 40.]])

In [38]:
sigma@x[:,0]

array([-2.54562438,  1.72347161])

In [39]:
sigma@x[:,1]

array([-31.91425695, -47.13840945])

In [40]:
x

array([[-0.82806723, -0.56062881],
       [ 0.56062881, -0.82806723]])

In [42]:
print('First principle component')
x[:,1]

First principle component


array([-0.56062881, -0.82806723])

In [44]:
print("Second principle component")
x[:,0]

Second principle component


array([-0.82806723,  0.56062881])

In [45]:
# Maximum will be first

In [46]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [47]:
# We have to transform this data into PC1, pc2 

In [48]:
A @ x[:,1]            # Multiplting my data with pc1 --> transformed data 

array([ -7.47835704,   7.21091862, -10.54893951,   0.26743842,
         3.07058247,   7.47835704])

In [49]:
pc1_arr = A @ x[:,1]

In [50]:
pc1_arr

array([ -7.47835704,   7.21091862, -10.54893951,   0.26743842,
         3.07058247,   7.47835704])

In [51]:
pc2_arr = A @ x[:,0]

In [52]:
pc2_arr

array([ 1.44019997, -0.05150393, -1.31144014, -1.38869604,  2.75164011,
       -1.44019997])

In [53]:
## Real data set of glass

In [55]:
df = pd.read_csv('glass.csv')

In [56]:
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [58]:
df = df.drop(columns=['Type'],axis=1)

In [59]:
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 9 columns]

In [60]:
# AVg of all is 0 or not

In [63]:
df.describe()    # --> mean check 0 or not and std = 1 we require

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe  
count  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009  
std      1.423153    0.497219    0.097439  
min      5.430000    0.000000    0.000000  
25%      8.240000    0.000000    0.000000  
50%      8.600000    0.000000    0.000000  
75%      9.172500    0.000000    0.100000  
max     16.190000    3.150000    0.510000

In [64]:
# Convert our all data into standar normal distribution

In [65]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [67]:
df_scaled = scaler.fit_transform(df)

In [68]:
df1 = pd.DataFrame(df_scaled)

In [69]:
df1.describe()

0             1             2             3             4  \
count  2.140000e+02  2.140000e+02  2.140000e+02  2.140000e+02  2.140000e+02   
mean  -2.877034e-14  2.191393e-15 -1.328117e-16 -2.988264e-16  9.525091e-16   
std    1.002345e+00  1.002345e+00  1.002345e+00  1.002345e+00  1.002345e+00   
min   -2.381516e+00 -3.286943e+00 -1.865511e+00 -2.318616e+00 -3.676472e+00   
25%   -6.082728e-01 -6.141580e-01 -3.957744e-01 -5.117560e-01 -4.800288e-01   
50%   -2.262293e-01 -1.323817e-01  5.527787e-01 -1.704602e-01  1.799655e-01   
75%    2.614331e-01  5.120326e-01  6.361680e-01  3.715977e-01  5.649621e-01   
max    5.137232e+00  4.875637e+00  1.254639e+00  4.125851e+00  3.570524e+00   

                  5             6             7             8  
count  2.140000e+02  2.140000e+02  2.140000e+02  2.140000e+02  
mean   3.527811e-17 -3.154278e-16 -6.640586e-17 -3.735330e-17  
std    1.002345e+00  1.002345e+00  1.002345e+00  1.002345e+00  
min   -7.639186e-01 -2.484084e+00 -3.528768e-01 -5.864509e-01  
25%   -5.756501e-01 -5.049657e-01 -3.528768e-01 -5.864509e-01  
50%    8.905322e-02 -2.514132e-01 -3.528768e-01 -5.864509e-01  
75%    1.735820e-01  1.518057e-01 -3.528768e-01  4.422417e-01  
max    8.780145e+00  5.094318e+00  5.997210e+00  4.659881e+00

In [76]:
sigma = np.cov(df1)

In [77]:
# Eigen value and vector

In [81]:
l , x = np.linalg.eig(df_scaled.T @ df_scaled/213)

In [82]:
l

array([2.52295323e+00, 2.05969694e+00, 1.41143951e+00, 1.16329842e+00,
       9.18293337e-01, 5.30112353e-01, 3.70690643e-01, 6.41527269e-02,
       1.61637096e-03])

In [83]:
x

array([[-0.54517662,  0.28568318,  0.08691083, -0.14738099,  0.0735427 ,
        -0.11528772, -0.08186724,  0.7522159 ,  0.02573194],
       [ 0.2581256 ,  0.27035007, -0.38491962, -0.49124204, -0.1536833 ,
         0.55811757, -0.14858006,  0.12769315, -0.31193718],
       [-0.11088095, -0.59355826,  0.00841796, -0.37878577, -0.12350912,
        -0.30818598,  0.20604537,  0.07689061, -0.57727335],
       [ 0.42870863,  0.29521154,  0.32923712,  0.13750592, -0.01410888,
         0.01885731,  0.69923557,  0.27444105, -0.19222686],
       [ 0.22883635, -0.15509891, -0.45870884,  0.65253771, -0.00850012,
        -0.08609797, -0.21606658,  0.37992298, -0.29807321],
       [ 0.21934405, -0.15397013,  0.66257412,  0.03853544,  0.30703984,
         0.24363237, -0.50412141,  0.10981168, -0.26050863],
       [-0.49230609,  0.3453798 , -0.00098473,  0.27644322,  0.18818774,
         0.14866937,  0.09913463, -0.39870468, -0.57932321],
       [ 0.25037512,  0.48470218,  0.07405473, -0.13317545, -0

In [84]:
# We are multiplying here like (214*9) (9*1) --> (214*1)

In [85]:
# manual ]
pc1_data = df_scaled @ x[:,0]

In [87]:
pc1_data.shape

(214,)